### ISSUE TITLE
main.exe just closes without any meaningful logs

### ISSUE THREAD

**Issue by qweryty** [qweryty/image-ai-utils-server#3]
Hello. I got through the guide and then main.exe finishes it closes.
I am on windows.
If I run python main.py on anaconda prompt I get the following:
(base) H:\DESCARGAS 1TB\image_ai_utils_windows\uvicorn>python main.py
Traceback (most recent call last):
File "H:\DESCARGAS 1TB\image_ai_utils_windows\uvicorn\main.py", line 1, in <module>
import asyncio
File "C:\Users\acani\anaconda3\lib\asyncio\__init__.py", line 8, in <module>
from .base_events import *
File "C:\Users\acani\anaconda3\lib\asyncio\base_events.py", line 18, in <module>
import concurrent.futures
File "C:\Users\acani\anaconda3\lib\concurrent\futures\__init__.py", line 8, in <module>
from concurrent.futures._base import (FIRST_COMPLETED,
File "C:\Users\acani\anaconda3\lib\concurrent\futures\_base.py", line 7, in <module>
import logging
File "H:\DESCARGAS 1TB\image_ai_utils_windows\uvicorn\logging.py", line 17, in <module>
class ColourizedFormatter(logging.Formatter):
AttributeError: partially initialized module 'logging' has no attribute 'Formatter' (most likely due to a circular import)

Also I don't know if it might be something related to the user and password of the edited env, but I don't know what that login is supoosed to be so didn't know what to edit there.. Thanks.

_Originally posted by @agustincaniglia in https://github.com/qweryty/image-ai-utils-server/issues/2#issuecomment-1236508593_

**Comment by agustincaniglia** [comment]
Here is what I get on Main now before it shutts down:
![mainexe](https://user-images.githubusercontent.com/25101051/188455993-65e22e23-6f19-43b2-ace5-27ecd0c73b38.png)

**Comment by agustincaniglia** [comment]
Also yes, I am using 4GBVRAM so I'll wait around here for when you release the optimized version. Thank you so much this looks so good.

**Comment by qweryty** [comment]
Added logs in fb33659, so now we can trace issues after main window is closed.

Out of memory issues can be tracked here: #1 so closing in favor of it
